apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    path: patches/ingress-nginx-service-nodeport.yaml
