apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  namespace: default
  labels:
    app: chatapp
    node.kubernetes.io/exclude-from-external-load-balancers: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp
        image: ghcr.io/lowjungxuan98/chatapp-development:20
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: kubeconfig
        secret:
          secretName: headlamp-admin-token
          items:
          - key: token
            path: token
      serviceAccountName: headlamp-admin
