apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.2/deploy/static/provider/cloud/deploy.yaml

patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    path: svc-nodeport-patch.yaml
