apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  POSTGRES_PRISMA_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9jaGF0YXBwP2Nvbm5lY3RfdGltZW91dD0xNQ==
  POSTGRES_URL_NON_POOLING: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9jaGF0YXBw
  AUTH_SECRET: TGhWUzduT1V2TndxbjR1dUl5VmZwWTBDVTVjR012TG9PQUsxT2lDMjFjPQ==
  AUTH_TRUST_HOST: dHJ1ZQ==
  NEXTAUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  SMTP_USERNAME: bWNzZ21zLmRldkBnbWFpbC5jb20=
  SMTP_PASSWORD: ZndkZSBucHR1IHBjemIgY3p5ag==
  EMAIL_FROM: bWNzZ21zLmRldkBnbWFpbC5jb20=
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
