apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: default
  labels:
    app.kubernetes.io/name: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headlamp
    spec:
      serviceAccountName: headlamp-admin
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:v0.34.0
        args:
        - "-in-cluster"
        - "-plugins-dir=/headlamp/plugins"
        - "-base-url=/headlamp"
        ports:
        - name: http
          containerPort: 4466
        readinessProbe:
          httpGet:
            path: /headlamp/
            port: 4466
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /headlamp/
            port: 4466
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
