apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    # - host: localhost
    #   http:
  - http:
      paths:
      - path: /headlamp
        pathType: Prefix
        backend:
          service:
            name: headlamp
            port:
              number: 80
