apiVersion: v1
kind: Service
metadata:
  name: headlamp-service
  namespace: default
  labels:
    app: headlamp
spec:
  selector:
    app: headlamp
  ports:
  - name: http
    port: 80
    targetPort: 4466
    protocol: TCP
  type: ClusterIP
